### PR TITLE
Added Crainal Capacity data

### PR DESCRIPTION
**Pull request by jegpeek**
Hope this fits in! Haven’t figured out how to add the figures yet, but should be fun. Tell me if you want some other formatting.

### CODE REVIEW

**Comment by barentsen** [comment]
Heyy @jegpeek that's cool!

Question I: is it correct that all the years are negative values?  (i.e. there's no post-jesus measurements?)

Question II: are you working on adding the plot, or would you like me to make one?  (The `plot_progress.py` script should work for this.)  I'd be happy to do it, just let me know.

**Comment by jegpeek** [comment]
1) yes, they are all measured in Mys before now, so I just did
2015-1e6*value. It's a little silly.

2) I thought I might leave that to you?

-Josh

On Thu, Sep 10, 2015 at 2:37 PM, Geert Barentsen notifications@github.com
wrote:

> Heyy that's cool!
> 
> Question I: is it correct that all the years are negative values? (i.e.
> there's no post-jesus measurements?)
> 
> Question II: are you working on adding the plot, or would you like me to
> make one? (The plot_progress.py script should work for this.) I'd be
> happy to do it, just let me know.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/barentsen/tech-progress-data/pull/1#issuecomment-139338181
> .

## 

Dr. Joshua E G Peek
Assistant Astronomer, Space Telescope Science Institute
Adjunct Research Scientist, Columbia University

STScI: 1 410 338 4561
Mobile: 1 510 299 4427

**Comment by barentsen** [comment]
Ok, cool!  I should be able to make a fancy plot this weekend.  Leaving the PR open for now so I don't forget :-)  Thanks @jegpeek!

**Comment by barentsen** [comment]
Hey @jegpeek, check this out!

The doubling rate of the cranial capacity is a MILLION times slower than Moore's law.  This really is a cool graph to contrast against the others.  Thanks again!

**Pull request merged**
